version: "3.7"

services:
  products-db:
    build:
      context: ./services/db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  api:
    restart: always
    build:
      context: ./services/api
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - "./services/api/:/usr/src/app/"
    environment:
      - DEBUG=1
      - SECRET_KEY=foo
      - DB_HOST=products-db
      - DB_NAME=products_dev
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_PORT=5432
    ports:
      - "8000:8000"
    depends_on:
      - products-db
